# Generated by Django 2.2.6 on 2019-11-17 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('level', models.IntegerField(choices=[(2, 'Adept'), (3, 'Expert'), (1, 'Apprentice'), (5, 'Legendary'), (0, 'Novice'), (4, 'Master')])),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('file', models.FileField(blank=True, upload_to='answers/%Y/%m/%d/')),
                ('url', models.URLField(blank=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('is_correct', models.BooleanField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='our_calendar.Task')),
            ],
            options={
                'db_table': 'answer_key',
            },
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('email', 'task'), name='unique key'),
        ),
    ]
