# Generated by Django 2.2.5 on 2019-11-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='level',
            field=models.IntegerField(choices=[(5, 'Legendary'), (4, 'Master'), (2, 'Adept'), (3, 'Expert'), (1, 'Apprentice'), (0, 'Novice')], default=None),
            preserve_default=False,
        ),
    ]
